name = "bspec-docs"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = ".vitepress/dist"

[env.production]
name = "bspec-docs"
route = "bspec.dev/*"

[env.preview]
name = "bspec-docs-preview"
